name: package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  package:
    strategy:
      matrix:
        arch: [ x64, aarch64 ]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: ${{ matrix.arch }}
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Install Dependencies
        run: |
          brew install sass/sass/sass
      - name: Package Mac
        if: matrix.arch == 'x64'
        run: ./gradlew packageMac -PpkgArch=amd64
      - name: Package Mac
        if: matrix.arch == 'aarch64'
        run: ./gradlew packageMac -PpkgArch=arm64
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uncle-novel-${{ matrix.arch }}
          path: |
            app/build/packager/*.dmg