name: package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
jobs:
  package:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: 'x64'
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew packageMac
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: uncle-novel.dmg
          path: |
            app/build/packager/*.dmg
            app/build/packager/*.pkg